package com.example

import android.content.ContentValues
import android.content.Context
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.widget.Toast
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.text.NumberFormat
import java.util.Locale

fun exportScheduleToCsv(context: Context, summary: LoanSummary) {
    val csvContent = buildString {
        append("Month,Open Balance,EMI,Principal,Interest,Prepayment,Close Balance,Rate (%)\n")
        summary.schedule.forEach { row ->
            append("${row.month},")
            append("%.2f,".format(row.openBalance))
            append("%.2f,".format(row.emi))
            append("%.2f,".format(row.principalPaid))
            append("%.2f,".format(row.interestPaid))
            append("%.2f,".format(row.prepayment))
            append("%.2f,".format(row.closeBalance))
            append("%.2f\n".format(row.rate))
        }
    }

    try {
        val fileName = "LoanSchedule_${System.currentTimeMillis()}.csv"
        var outStream: OutputStream? = null

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val resolver = context.contentResolver
            val contentValues = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                put(MediaStore.MediaColumns.MIME_TYPE, "text/csv")
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
            if (uri != null) {
                outStream = resolver.openOutputStream(uri)
            }
        } else {
            val dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            val file = File(dir, fileName)
            outStream = FileOutputStream(file)
        }

        outStream?.use {
            it.write(csvContent.toByteArray())
        }
        Toast.makeText(context, "Saved to Downloads", Toast.LENGTH_LONG).show()
    } catch (e: Exception) {
        e.printStackTrace()
        Toast.makeText(context, "Failed to export", Toast.LENGTH_SHORT).show()
    }
}

fun exportScheduleToPdf(context: Context, summary: LoanSummary, input: LoanInput) {
    val pdfDocument = PdfDocument()
    val pageWidth = 595
    val pageHeight = 842

    val textPaint = Paint().apply {
        textSize = 10f
        color = android.graphics.Color.BLACK
        isAntiAlias = true
    }

    val boldTextPaint = Paint().apply {
        textSize = 10f
        color = android.graphics.Color.BLACK
        fontWeight = android.graphics.Typeface.BOLD
        isAntiAlias = true
    }

    val titlePaint = Paint().apply {
        textSize = 18f
        color = android.graphics.Color.rgb(0, 97, 164) // md_theme_light_primary
        fontWeight = android.graphics.Typeface.BOLD
        isAntiAlias = true
    }

    val subtitlePaint = Paint().apply {
        textSize = 10f
        color = android.graphics.Color.GRAY
        isAntiAlias = true
    }

    val headerPaint = Paint().apply {
        textSize = 10f
        color = android.graphics.Color.BLACK
        fontWeight = android.graphics.Typeface.BOLD
        isAntiAlias = true
    }

    val linePaint = Paint().apply {
        strokeWidth = 1f
        color = android.graphics.Color.LTGRAY
        style = Paint.Style.STROKE
    }

    val bgPaint = Paint().apply {
        color = android.graphics.Color.rgb(245, 245, 245)
        style = Paint.Style.FILL
    }

    val currencyFormat = NumberFormat.getCurrencyInstance(Locale("en", "IN")).apply {
        maximumFractionDigits = 0
    }

    val rows = summary.schedule
    val totalRows = rows.size

    val firstPageRows = 28
    val otherPageRows = 34

    var currentIdx = 0
    var pageNumber = 1

    val totalPages = if (totalRows <= firstPageRows) {
        1
    } else {
        1 + kotlin.math.ceil((totalRows - firstPageRows).toDouble() / otherPageRows).toInt()
    }

    while (currentIdx < totalRows) {
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas

        if (pageNumber == 1) {
            // First page header
            canvas.drawText("Home Loan Amortization Schedule", 36f, 60f, titlePaint)
            canvas.drawText("Generated by Home Loan Pro", 36f, 76f, subtitlePaint)

            // Draw parameter box
            canvas.drawRect(36f, 90f, (pageWidth - 36).toFloat(), 155f, bgPaint)
            canvas.drawRect(36f, 90f, (pageWidth - 36).toFloat(), 155f, linePaint)

            canvas.drawText("Principal Amount: ${currencyFormat.format(input.principal)}", 50f, 110f, boldTextPaint)
            canvas.drawText("Interest Rate: ${input.annualInterestRate}%", 50f, 125f, textPaint)
            canvas.drawText("Tenure: ${input.tenureMonths} Months", 50f, 140f, textPaint)

            canvas.drawText("Total Payment: ${currencyFormat.format(summary.totalPayment)}", 300f, 110f, boldTextPaint)
            canvas.drawText("Total Interest: ${currencyFormat.format(summary.totalInterest)}", 300f, 125f, textPaint)
            if (summary.savingsInterest > 0) {
                canvas.drawText("Interest Saved: ${currencyFormat.format(summary.savingsInterest)}", 300f, 140f, textPaint)
            }

            // Table headers
            val headerY = 180f
            canvas.drawText("Month", 36f, headerY, headerPaint)
            canvas.drawText("EMI", 110f, headerY, headerPaint)
            canvas.drawText("Principal", 190f, headerY, headerPaint)
            canvas.drawText("Interest", 280f, headerY, headerPaint)
            canvas.drawText("Prepayment", 370f, headerY, headerPaint)
            canvas.drawText("Balance", 460f, headerY, headerPaint)

            canvas.drawLine(36f, headerY + 6f, (pageWidth - 36).toFloat(), headerY + 6f, linePaint)

            // Draw rows
            var yPos = 205f
            val limit = minOf(currentIdx + firstPageRows, totalRows)
            for (i in currentIdx until limit) {
                val row = rows[i]
                if (i % 2 == 1) {
                    canvas.drawRect(36f, yPos - 12f, (pageWidth - 36).toFloat(), yPos + 6f, bgPaint)
                }

                canvas.drawText(formatMonthYear(input.startDateMs, row.month), 36f, yPos, textPaint)
                canvas.drawText(currencyFormat.format(row.emi), 110f, yPos, textPaint)
                canvas.drawText(currencyFormat.format(row.principalPaid), 190f, yPos, textPaint)
                canvas.drawText(currencyFormat.format(row.interestPaid), 280f, yPos, textPaint)
                canvas.drawText(if (row.prepayment > 0) currencyFormat.format(row.prepayment) else "Rs. 0", 370f, yPos, textPaint)
                canvas.drawText(currencyFormat.format(row.closeBalance), 460f, yPos, textPaint)

                canvas.drawLine(36f, yPos + 6f, (pageWidth - 36).toFloat(), yPos + 6f, linePaint)
                yPos += 22f
            }
            currentIdx = limit
        } else {
            // Subsequent pages table header
            val headerY = 60f
            canvas.drawText("Month", 36f, headerY, headerPaint)
            canvas.drawText("EMI", 110f, headerY, headerPaint)
            canvas.drawText("Principal", 190f, headerY, headerPaint)
            canvas.drawText("Interest", 280f, headerY, headerPaint)
            canvas.drawText("Prepayment", 370f, headerY, headerPaint)
            canvas.drawText("Balance", 460f, headerY, headerPaint)

            canvas.drawLine(36f, headerY + 6f, (pageWidth - 36).toFloat(), headerY + 6f, linePaint)

            var yPos = 85f
            val limit = minOf(currentIdx + otherPageRows, totalRows)
            for (i in currentIdx until limit) {
                val row = rows[i]
                if (i % 2 == 1) {
                    canvas.drawRect(36f, yPos - 12f, (pageWidth - 36).toFloat(), yPos + 6f, bgPaint)
                }

                canvas.drawText(formatMonthYear(input.startDateMs, row.month), 36f, yPos, textPaint)
                canvas.drawText(currencyFormat.format(row.emi), 110f, yPos, textPaint)
                canvas.drawText(currencyFormat.format(row.principalPaid), 190f, yPos, textPaint)
                canvas.drawText(currencyFormat.format(row.interestPaid), 280f, yPos, textPaint)
                canvas.drawText(if (row.prepayment > 0) currencyFormat.format(row.prepayment) else "Rs. 0", 370f, yPos, textPaint)
                canvas.drawText(currencyFormat.format(row.closeBalance), 460f, yPos, textPaint)

                canvas.drawLine(36f, yPos + 6f, (pageWidth - 36).toFloat(), yPos + 6f, linePaint)
                yPos += 22f
            }
            currentIdx = limit
        }

        // Draw footer
        canvas.drawLine(36f, 810f, (pageWidth - 36).toFloat(), 810f, linePaint)
        canvas.drawText("Page $pageNumber of $totalPages", (pageWidth - 110).toFloat(), 825f, textPaint)
        canvas.drawText("Home Loan Pro Amortization Plan", 36f, 825f, subtitlePaint)

        pdfDocument.finishPage(page)
        pageNumber++
    }

    try {
        val fileName = "LoanSchedule_${System.currentTimeMillis()}.pdf"
        var outStream: OutputStream? = null

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val resolver = context.contentResolver
            val contentValues = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
            if (uri != null) {
                outStream = resolver.openOutputStream(uri)
            }
        } else {
            val dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            val file = File(dir, fileName)
            outStream = FileOutputStream(file)
        }

        outStream?.use {
            pdfDocument.writeTo(it)
        }
        Toast.makeText(context, "Saved PDF to Downloads", Toast.LENGTH_LONG).show()
    } catch (e: Exception) {
        e.printStackTrace()
        Toast.makeText(context, "Failed to export PDF", Toast.LENGTH_SHORT).show()
    } finally {
        pdfDocument.close()
    }
}
